### ISSUE TITLE
Cardinality of problem details object members

### ISSUE THREAD

**Issue by tdonker** [ietf-wg-httpapi/rfc7807bis#25]
When reading:

https://ietf-wg-httpapi.github.io/rfc7807bis/draft-ietf-httpapi-rfc7807bis.html

it's not entrirely clear which member field of the problem details object (type, status, title, detail, instance) is mandatory and which is optional. Is it correct to state that only the 'type' member is mandatory and all others are optional?

**Comment by sazzer** [comment]
As I understand it, none of them are mandatory.

Under `type` it states:
> When this member is not present, its value is assumed to be "about:blank".

Under `status` it states: (Emphasis mine)
> The "status" member, **if present**, is only advisory

Under `title` it states:
> The "title" string is advisory and included only for users who are not aware of the semantics of the URI and do not have the ability to discover them

Under `detail` it states: (Emphasis mine)
> The "detail" member, **if present**

And `instance` doesn't actually say anything one way or the other, but I've always assumed it's present only if there is anything to include.

**Comment by asbjornu** [comment]
Yeah, all of them are optional and `type` has a default value.

**Comment by tdonker** [comment]
Thanks for the quick reply. The cardinality of the 'type' member made doubt a little bit - but thats clear now.

**Comment by sazzer** [comment]
I'm not 100% sure I agree that they all *should* be optional. In some ways
that makes it just a little bit harder to work with, since the spec defines
5 fields that are all optional and allows you to add arbitrary other fields
as well it means that almost any JSON object is a valid Problem Details
object. The only actual rules end up being "Any fields that have these 5
names must have the correct meaning" and nothing else can be relied upon.

For example, the following is a perfectly legal response:
```
HTTP/1.1 404 Not Found
Content-Type: application/problem+json

{
    "id": "12345"
}
```

**Comment by tdonker** [comment]
OK - reopened the issue ...
