### ISSUE TITLE
Resolvability of IANA URIs

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/rfc7807bis#62]
As discussed in Carsten's feedback, we should note that IANA URLs with fragment identifiers are currently not resolveable to the fragment identifier.

**Comment by asbjornu** [comment]
Can we assist IANA in making this a supported use case? From the outset, it seems like supporting fragment identifiers is trivial. I saw the discussion about not being able to mandate an HTML structure and I don't really know enough about IANA's inner workings or process to understand what the problem of supporting fragment identifiers really is. If anyone can elaborate on that, I'd be grateful.

**Comment by mnot** [comment]
We can start that discussion this week, but it's a much larger coordination (they'll want to do it for *all* registries), so we shouldn't take a dependency on it.

**Comment by asbjornu** [comment]
I see. Yeah, that makes sense. How does this fit in with the general UX and design work I've seen IETF has been RFQ-ing about lately? Does the scope of that work include any of IANA's areas? If not, perhaps we can piggyback on the general IETF design to improve the look, feel and UX of IANA's registries?

**Comment by mnot** [comment]
There is a lot of friction there, but we'll see. Please be patient :)

**Comment by dret** [comment]
On 2022-11-08 01:51, Asbjørn Ulsberg wrote:
> I see. Yeah, that makes sense. How does this fit in with the general UX 
> and design work I've seen IETF has been RFQ-ing about lately? Does the 
> scope of that work include any of IANA's areas? If not, perhaps we can 
> piggyback on the general IETF design to improve the look, feel and UX of 
> IANA's registries?

just piggybacking on a recent trend in the API space i think what we 
should really try to do is improve the DX of their registry pages: i.e., 
given that there isn't an actual registry API (there isn't, right?), 
then it would be reasonable and probably the easiest way forward to turn 
their registry pages into their API.

they have some good start because they're using XHTML. a long time ago i 
did experiment a bit with simply processing everything as one XML API. 
that didn't go great but sort of worked after a bit of clean-up and 
adding some special case rules. i think improving this wouldn't be too 
hard, if they're willing to make that a goal.

**Comment by sazzer** [comment]
It's not a small change, but I wonder if theres any benefit in making those
pages instead be just XML files that then link to an appropriate XSLT
stylesheet whichi re-renders them as HTML for browsers? That way, API
consumers could get the XML version instead and have a slightly easier time
parsing them, whilst human consumers still get to see them in an
easier-to-read format in their browsers.

Cheers
-- 
Graham Cox

**Comment by mnot** [comment]
Please understand that how IANA does its job is regulated by a contract and some oversight bodies, and so we can't go in and say 'do it this way.' We can start that process but it's not going to happen on this issue. Let's constrain this discussion to what should happen in _this_ specification.

**Comment by sdatspun2** [comment]
> As discussed in Carsten's feedback, we should note that IANA URLs with fragment identifiers are currently not resolveable to the fragment identifier.

Record keeping nit: is there a link to that discussion which can be addd to this issue?
