### ISSUE TITLE
How should Accept header be used by the server?

### ISSUE THREAD

**Issue by maricn** [ietf-wg-httpapi/rfc7807bis#75]
In some examples ([[1]](https://github.com/ietf-wg-httpapi/rfc7807bis/blob/ca4dd4b6159b620d81226e20dac3e124a629e68f/draft-ietf-httpapi-rfc7807bis.md?plain=1#L129) and [[2]](https://github.com/ietf-wg-httpapi/rfc7807bis/blob/ca4dd4b6159b620d81226e20dac3e124a629e68f/draft-ietf-httpapi-rfc7807bis.md?plain=1#L160)) at current state of `main` branch, there are different values of the `Accept` request header - `application/json` and `application/json, application/problem+json`. They are interchangeably used without any comment or note. This creates confusion and it could be helpful to have a clarification of how does the Accept header influence the response.

**Comment by sazzer** [comment]
RFC-6838 defines "Structured Syntax Name Suffixes", and in particular it defines that anything with a `+json` suffix should be treated as `application/json` unless there are stricter rules for that exact media type.

As such, it seems reasonable (to me at least, and I'm not an expert!) to reply with `application/problem+json` to something that only accepts `application/json` - since, per those rules, `application/problem+json` can be interpreted as valid `application/json` as well.

**Comment by maricn** [comment]
@sazzer thank you for the prompt response - i find that logic very reasonable! 

it is also implicit in the examples i linked in the original post, but considering how the RFC at hand defines `application/problem+json`, i would personally still find it valuable if that piece of "sidenote" information would be explicit in the document..

**Comment by sazzer** [comment]
Personally, I agree, and I think that having the examples be inconsistent isn't great. I was just explaining how they are both technically valid :)
